<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class task extends Model
{
    protected $guarded = [];

    protected $touches = ['project'];

    protected $casts = [

        'completed' => 'boolean'

    ];

    protected static function boot(){

        parent::boot(); // TODO: Change the autogenerated sub

        static::created(function ($task){

            $task->project->recordActivity('created_task');

        });

        static::updated(function ($task){

            $task->project->recordActivity('completed_task');

        });

    }

    public function complete()
    {

        $this->update(['completed' => true]);

    }

    

    public function project()
    {
    	return $this->belongsTo(Project::class);
    }

    public function path()
    {
    	return "/projects/{$this->project->id}/tasks/{$this->id}";
    }
}
