<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class task extends Model
{
    protected $guarded = [];

    protected $touches = ['project'];

    protected static function boot(){

        parent::boot(); // TODO: Change the autogenerated sub

        static::created(function ($task){

            Activity::create([

                'project_id' => $task->project->id,

                'description' => 'created_task'

            ]);

        });

        static::updated(function ($task){

            Activity::create([

                'project_id' => $task->project->id,

                'description' => 'completed_task'

            ]);

        });

    }

    

    public function project()
    {
    	return $this->belongsTo(Project::class);
    }

    public function path()
    {
    	return "/projects/{$this->project->id}/tasks/{$this->id}";
    }
}
